from code.tests import testingtools
from code.search_code import searchdata
import pytest


def expected_tf():
    return [('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'coconut', 0.05405405405405406),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'kiwi', 0.02702702702702703),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'banana', 0.10810810810810811),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'fig', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'apple', 0.16216216216216217),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'cherry', 0.08108108108108109),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'lime', 0.05405405405405406),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'pear', 0.13513513513513514),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-9.html', 'tomato', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'apple', 0.18181818181818182),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'kiwi', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'coconut', 0.09090909090909091),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'banana', 0.18181818181818182),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'papaya', 0.18181818181818182),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'lime', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'blueberry', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'cherry', 0.09090909090909091),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-5.html', 'fig', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'apple', 0.06666666666666667),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'kiwi', 0.06666666666666667),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'coconut', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'banana', 0.06666666666666667),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'papaya', 0.2),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'lime', 0.26666666666666666),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'blueberry', 0.06666666666666667),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-3.html', 'cherry', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'apple', 0.17391304347826086),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'kiwi', 0.08695652173913043),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'coconut', 0.13043478260869565),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'banana', 0.21739130434782608),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'papaya', 0.043478260869565216),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'lime', 0.08695652173913043),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-0.html', 'tomato', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-1.html', 'apple', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-1.html', 'kiwi',  0.05),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-1.html', 'coconut', 0.05),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-1.html', 'lime', 0.1),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-1.html', 'blueberry', 0.2),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-1.html', 'cherry', 0.15),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'apple', 0.125),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'kiwi', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'coconut', 0.03125),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'banana', 0.125),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'papaya', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'pear', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-4.html', 'tomato', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-2.html', 'banana', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-2.html', 'papaya', 0.14285714285714285),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-2.html', 'lime', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-2.html', 'cherry', 0.14285714285714285),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-2.html', 'fig', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-2.html', 'pear', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'apple', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'apple', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'coconut', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'banana', 0.125),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'lime', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'blueberry', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-6.html', 'cherry', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'kiwi', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'coconut', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'banana', 0.125),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'papaya', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'lime', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'fig', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'pear', 0.0625),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-7.html', 'tomato', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-8.html', 'apple', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-8.html', 'kiwi', 0.25),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-8.html', 'coconut', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-8.html', 'banana', 0.25),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-8.html', 'lime', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N-8.html', 'cherry', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N.html', 'apple', 0.0),
            ('http://people.scs.carleton.ca/~davidmckenney/tinyfruits/N.html', 'kiwi', 0.0)
            ]


@pytest.mark.parametrize('url, fruit, expected', expected_tf())
def test_tf(run_crawler, url, fruit, expected):
    result = searchdata.get_tf(url, fruit)
    assert testingtools.compare_doubles(result, expected)
